name: say hello

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "hola mundo"
      - name: Dime la fecha
        run: date
      - run: ls -l
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependecies
        run: npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}

   
